package cassette_test

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"

	"github.com/MarkRosemaker/openapi-enrich/cassette"
)

// interactions stand in for those read with cassette.InteractionsReadFile("api/interactions.json").
var interactions = cassette.Interactions{{
	Request: cassette.Request{
		Method: http.MethodGet,
		URL:    url.URL{Scheme: "https", Host: "api.example.com", Path: "/users/me"},
	},
	Response: cassette.Response{
		StatusCode: http.StatusOK,
		Headers:    http.Header{"Content-Type": {"application/json"}},
		Body:       cassette.Body(`{"name":"Alice"}`),
	},
}}

// Mock a client in tests: requests are answered from the recordings, and nothing reaches the network. A client
// generated by openapi-codegen takes it as WithHTTPClient(&http.Client{Transport: cassette.Replay(ias)}).
func ExampleReplay() {
	client := &http.Client{Transport: cassette.Replay(interactions)}

	rsp, err := get(client, "https://api.example.com/users/me")
	if err != nil {
		panic(err)
	}
	defer rsp.Body.Close()

	body, _ := io.ReadAll(rsp.Body)
	fmt.Println(rsp.StatusCode, string(body))

	_, err = get(client, "https://api.example.com/users/42")
	fmt.Println(err)

	// Output:
	// 200 {"name":"Alice"}
	// Get "https://api.example.com/users/42": GET https://api.example.com/users/42: no recorded interaction
}

// Record calls: what has no recording is sent, here to a stand-in for the API, and recorded beside what was replayed.
// Write them with rec.Interactions().WriteFile("api/interactions.json"), which masks credentials first.
func ExampleReplay_record() {
	api := roundTripFunc(func(*http.Request) (*http.Response, error) {
		return &http.Response{StatusCode: http.StatusNoContent, Body: http.NoBody}, nil
	})

	rec := cassette.Replay(interactions, cassette.RecordMisses(api))
	client := &http.Client{Transport: rec}

	for _, u := range []string{"https://api.example.com/users/me", "https://api.example.com/ping"} {
		rsp, err := get(client, u)
		if err != nil {
			panic(err)
		}

		rsp.Body.Close()
	}

	for _, ia := range rec.Interactions() {
		fmt.Println(ia.Request.Method, &ia.Request.URL, ia.Response.StatusCode)
	}

	// Output:
	// GET https://api.example.com/users/me 200
	// GET https://api.example.com/ping 204
}

// Test strictly, as openapi-codegen's generated tests do: each call must be the next recording, headers included but
// the User-Agent, and every recording must be called.
func ExampleInOrder() {
	rec := cassette.Replay(interactions, cassette.InOrder(),
		cassette.WithMatcher(cassette.MatchRequest(cassette.CompareHeaders("User-Agent"))))
	client := &http.Client{Transport: rec}

	_, err := get(client, "https://api.example.com/users/42")
	fmt.Println(err)
	fmt.Println(len(rec.Unused()), "never called")

	// Output:
	// Get "https://api.example.com/users/42": interaction #0: got URL https://api.example.com/users/42, want https://api.example.com/users/me
	// 1 never called
}

// get sends a GET request for u with client.
func get(client *http.Client, u string) (*http.Response, error) {
	req, err := http.NewRequestWithContext(context.Background(), http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}

	return client.Do(req)
}
